import Image from 'next/image'
import React from 'react'
import Login from '/public/loginimage.png'
import Head from 'next/head'
import { Surveyform } from '../src/components/Forms/Surveyform'
 
function card() {
  return (
    <div class="flex flex-row w-full bg-white-900">
      <Head>
        <title>Survey form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/login.png" />
        <link href='//fonts.googleapis.com/css?family=Montserrat:thin,extra-light,light,100,200,300,400,500,600,700,800' 
         rel='stylesheet' type='text/css'></link>
      </Head>
     <Surveyform/>
    </div>
 
  )
}
 
export default card

