import Image from 'next/image'
import React from 'react'
import Login from '/public/loginimage.png'
import Camila from '/public/camila.png'
import Head from 'next/head'
 
function card() {
  return (
    <div class="flex flex-row w-full bg-white-900">
      <Head>
        <title>My Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/login.png" />
        <link href='//fonts.googleapis.com/css?family=Montserrat:thin,extra-light,light,100,200,300,400,500,600,700,800' 
         rel='stylesheet' type='text/css'></link>
      </Head>
      <main class="p-8 w-full h-screen flex flex-column justify-center bg-gradient-to-t from-yellow-100 via-yellow-300 to-yellow-500">
      <div class="flex flex-col bg-white w-4/5 h-5/6 shadow-2xl rounded-3xl p-8 mt-14 justify-center">
        <div class="h-1 mt-1 bg-gradient-to-r from-yellow-200 via-yellow-400 to-yellow-700 ">
                
           

        </div>

       
        </div>
      </main>
    </div>
 
  )
}
 
export default card

