import React from "react";
import Image from "next/image";
import Head from "next/head";
import { Elearningsidenav } from "../src/components/Elearning/Elearningsidenav";
import { Elearningtopnav } from "../src/components/Elearning/Elearningtopnav";

function elearninghome(){
    return (
        <div className="flex flex-row w-full bg-white-900">
          <Head>
            <title>E-learning</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/login.png" />
           
          </Head>
          <div className="flex flex-row w-full bg-white-900">
          <Elearningsidenav/>
          <Elearningtopnav/>
          </div>
         
        </div>
      );

}
export default elearninghome;