import React from "react";
import Image from "next/image";
import Head from "next/head";
import { Elearningsidenav } from "../src/components/Elearning/Elearningsidenav";
import { Elearningtopnav } from "../src/components/Elearning/Elearningtopnav";
import { Sidenav } from "../src/components/Elearning/Sidenav";

function elearninghome() {
  return (
    <div className="">
      <Head>
        <title>E-learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/login.png" />
      </Head>
      <div className="grid grid-row-2 h-screen">
        <div className="lg:w-2/12 h-screen bg-[#00C285]">
          <Sidenav />
        </div>

        <div className="flex flex-column absolute w-screen h-20 bg-[#FAFFFD] lg:ml-[264px] shadow-sm border">
          <Elearningtopnav />
          {/* <Elearningcarousel/>
            <Elearningsubjects />
            <Elearningliveclasses/> */}
        </div>
      </div>
    </div>
  );
}
export default elearninghome;
