import React from "react";
import Image from "next/image";
import Head from "next/head";
import { Elearningsidenav } from "../src/components/Elearning/Elearningsidenav";
import { Elearningtopnav } from "../src/components/Elearning/Elearningtopnav";
import { Sidenav } from "../src/components/Elearning/Sidenav";
import { Rightpart } from "../src/components/Elearning/Rightpart";

function elearninghome() {
  return (
    <div className="">
      <Head>
        <title>E-learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/login.png" />
      </Head>
      <div className="flex flex-row-2 w-screen h-screen">
        <Sidenav />
        <Rightpart />
      </div>
    </div>
  );
}
export default elearninghome;
