import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          React Projects
        </h1>
          <br></br>
        <h2>
         Click below to view the projects
        </h2>
          <br></br>
        <div>
          <button className={styles.buttonproject}><a href="http://localhost:3000/signup">Signup Page - 1</a></button>
          <button className={styles.buttonproject}><a href="http://localhost:3000/login">Login Page - 2</a></button>
          <button className={styles.buttonproject}><a href="http://localhost:3000/otp">Verify OTP Page - 3</a></button>
          
        </div>

      </main>
    </div>
  )
}
