import Image from "next/image";
import React from "react";
import Login from "/public/loginimage.png";
import Head from "next/head";
import Loginform from "../src/components/Login/Loginform";
import Loginleft from "../src/components/Login/Loginleft";

function login() {
  return (
    <div class="flex flex-row w-full bg-white-900">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/login.png" />
       
      </Head>
      <Loginleft />

      <Loginform />
    </div>
  );
}

export default login;
