
import React from "react";
import Login from "/public/loginimage.png";
import Head from "next/head";
import Signupform from "../src/components/Signup/Signupform";
import Signupleft from "../src/components/Signup/Signupleft";

function signup() {
  return (
    <div className="grid grid-row-2 md:grid-cols-2 h-screen">
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/signup.png" />
        <link
          href="//fonts.googleapis.com/css?family=Montserrat:thin,extra-light,light,100,200,300,400,500,600,700,800"
          rel="stylesheet"
          type="text/css"
        ></link>
      </Head>
      <Signupleft/>
     
      <Signupform />
    
      </div>
  );
}

export default signup;
